### ISSUE TITLE
Error while setting up on Home Assistant 2020.12.2

### ISSUE THREAD

**Issue by BillyFKidney** [mtgeekman/Home_Assistant_NeoSmartBlinds#1]
When trying to setup the Neo Smart Blinds custom integration the following error appears in my logs.

`Logger: homeassistant.components.cover
Source: custom_components/neosmartblinds/cover.py:98 
Integration: Cover (documentation, issues) 
First occurred: 8:33:43 PM (1 occurrences) 
Last logged: 8:33:43 PM

Error while setting up neosmartblinds platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neosmartblinds/cover.py", line 67, in setup_platform
    cover = NeoSmartBlindsCover(
  File "/config/custom_components/neosmartblinds/cover.py", line 98, in __init__
    self.hass.data[DATA_NEOSMARTBLINDS].append(self._client)
AttributeError: 'NoneType' object has no attribute 'data'`

**Comment by clara-j** [comment]
I am having the same issue on startup.  Not sure what is causing the issue.  Were you ever able to solve this?

**Comment by clara-j** [comment]
Actually I just found if I use the copy from the release v11 it seems to be working.

**Comment by JamieP83** [comment]
I use this fork and its great
https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds

**Comment by mtgeekman** [comment]
I have not been good about keeping track of this repo lately.  

The release is the only version that will currently work.
