### ISSUE TITLE
K2 motor not working

### ISSUE THREAD

**Issue by appannu** [mtgeekman/Home_Assistant_NeoSmartBlinds#11]
Hi, I am having issues getting the integration to work with some blinds that have a "K2" motor code. It works with other blinds in my setup that have motor code "BF". Both motor types work in the neosmartblinds app. I have tried resetting the controller and deleting the files from HA and its still not working with the "K2" motors. I don't get any error codes in my log when trying to move the "K2" blinds up or down. Also I believe there is communication between the hub and HA because when I try to move the "K2" motors up or down, one of my fans (which is also RF) turns on/off. But the signal sent doesn't control my blinds. Any help would be appreciated.

**Comment by mtgeekman** [comment]
can you share your config for the blinds?

**Comment by appannu** [comment]
- platform: neosmartblinds
  name: Family Room Blinds
  host: 192.168.[static ip of hub]
  hub_id: [hub_code]
  protocol: http
  port: 8838
  blind_code: [blind code]
  close_time: 30

This is the code for both the K2 motors and the bf motors. The only difference is the blind_code.

**Comment by Bacichetti** [comment]
Can you share the first 4 digits from your hub_id?
There is a new configuration needed for some specific motors when using a
new version of the hub.


Antonio Bacichetti
*Chief Engineer*
*Neo Smart Blinds*
9386, Boulevard Viau

Saint Leonard (QC) H1R 3B5
neosmartblinds.com

**Comment by appannu** [comment]
hub_id: TtKRKT_OVUmnRRyLA-[....]

**Comment by Bacichetti** [comment]
@mtgeekman ,

New controllers (model C-BR300) need to have the motor code added to the command for certain motor codes.
I don't know all the parts that must be changed in the integration. Here is what has to change at the last part of the implementation:

Implement a new configuration parameter "motor_code", that's always 2 digits (no,k1,k2,rx,dy,bf,tb etc...). It's always preceded by "!"
command example: 123.123-05!k2

TCP:
command = self._device + "-" + code + _**"!" + motor_code**_ + '\r\n'

HTTP:
params = {'id': self._the_id, 'command': self._device + "-" + command + _**"!" + motor_code**_, 'hash': str(time.time()).strip(".")[-7:]}


To avoid breaking older integrations. If the new "motor_code" was not found in the configuration file, just send the commands without the "!" and the motor_code.

**Comment by mtgeekman** [comment]
@appannu can you download the files from the repository and place them on your home assistant.  I have added an option for "motor_code"  in the configs.  

I am working on updating the documentation now. 

@Bacichetti Thanks for the info!

**Comment by appannu** [comment]
Thanks, I'll try it when I get home and let you know if it works.

**Comment by appannu** [comment]
It works, thanks!
