### ISSUE TITLE
Favorite position

### ISSUE THREAD

**Issue by akayami** [mtgeekman/Home_Assistant_NeoSmartBlinds#2]
First of all, thanks for maintaining this. I've setup some blinds using this, and I can open and close them fine. 

The only thing I'm trying to understand is how to trigger the favorite position using the lovelace UI. Maybe you can help me with that ? Thanks.

**Comment by ZEi20T** [comment]
This is what i use:

type: button
tap_action:
  action: call-service
  service: cover.set_cover_position
  service_data:
    position: 50
    entity_id: cover.back_window
name: Back Shutter Half-Way
icon: 'mdi:download'
show_state: false
show_icon: true
show_name: true

I already used the Neo Smart Blinds app to set the favorite position.

**Comment by mtgeekman** [comment]
Setting the position to 50 is exactly how the favorite position is triggered.
