### ISSUE TITLE
2022.3.0 HA docker version breaks neosmartblinds (I think)

### ISSUE THREAD

**Issue by martindell** [mtgeekman/Home_Assistant_NeoSmartBlinds#22]
I'm running the HA docker on Unraid
```
Version | core-2022.3.0
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.28-Unraid
CPU Architecture | x86_64
Timezone | Europe/London
```
In the HA logs yesterday, after a docker upgrade I saw
```
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-03 12:54:25 ERROR (SyncWorker_0) [homeassistant.util.package] Unable to install package requests==2.24.0: ERROR: Cannot install requests==2.24.0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-03-03 12:54:25 ERROR (MainThread) [homeassistant.config] Platform error: cover - Requirements for neosmartblinds not found: ['requests==2.24.0'].
```
I downgraded the HA docker version to 2022.2.0 and the blinds work again / no errors in the log.  All was working fine before the docker upgrade and all OK now

**Comment by keithr59** [comment]
I have experienced the same problem running Home Assistant OS

I believe it is due to a new pip dependency resolver introduced in 2022.3.0.

See the _Integration dependencies and Python pip_ section in the [release notes](https://www.home-assistant.io/blog/2022/03/02/release-20223/).

**Comment by mtgeekman** [comment]
> I have experienced the same problem running Home Assistant OS
> 
> I believe it is due to a new pip dependency resolver introduced in 2022.3.0.
> 
> See the _Integration dependencies and Python pip_ section in the [release notes](https://www.home-assistant.io/blog/2022/03/02/release-20223/).

I believe you might be correct on this.  I'll get a new update pushed today at some point that will hopefully fix this. testing this morning to make sure it will work in the latest HA.

**Comment by mtgeekman** [comment]
@martindell 

I have put up a new release, 2.1.  with a fix.  it is working great on my installation after the change.  Please give it a shot and let me know if it's working for you as well.

**Comment by keithr59** [comment]
> I have put up a new release, 2.1. with a fix. it is working great on my installation after the change. Please give it a shot and let me know if it's working for you as well.

I can confirm that it works on my installation also. Thank you very much.

**Comment by martindell** [comment]
> I have put up a new release, 2.1. with a fix. it is working great on my installation after the change. Please give it a shot and let me know if it's working for you as well.

Awesome, thank you.  Works fine for me in HA 2022.2 and 2022.3 👍
