### ISSUE TITLE
HACS Implementation add an extra sub-folder

### ISSUE THREAD

**Issue by jjpeet** [mtgeekman/Home_Assistant_NeoSmartBlinds#23]
Hi,
When I install via HACS, the component is not loading. I suspect that when I load the custom component via HACS, it is being installed in config/custom_components/neosmartblinds/neosmartblinds.

I suspect the issue is that there's one extra sub folder that needs to be removed.  So it should go into;
config/custom_components/neosmartblinds

I've verified that the issue is fixed when I manually shift the files to this correct location.

Thx
JP

**Comment by adepssimius** [comment]
I can confirm that this is the case. The fix above works. This is the only HACS integration I have that specifies a zip realease in the hacs.json. HACS only seems to see a 2.1, not a 2.1h release, so I wonder if your fix isn't working for HACS just yet.

**Comment by mtgeekman** [comment]
Can any of you test this with the latest release?

**Comment by jjpeet** [comment]
Hi @mtgeekman 

Yes I installed yesterday. 

Now the component is creating (under custom_component/neosmartblinds) more sub folders - /custom_component/neosmartblinds. 

So I needed to grab the files and bring them back two folder levels to make it work. 

Thx
JP

**Comment by mtgeekman** [comment]
> 

hah!, figures.  but that gives me enough info to potentially have a fix. 

Thank you!  

Should have a 2.2.1 out in a couple of hours after I get back home.

**Comment by mtgeekman** [comment]
@jjpeet if you are up for it, I just pushed a new release that I hope will fix the folder issue.

**Comment by keithr59** [comment]
@mtgeekman I have installed the latest release using HACS and everything looks good.
