### ISSUE TITLE
Version issue in manifest file

### ISSUE THREAD

**Issue by marshes** [mtgeekman/Home_Assistant_NeoSmartBlinds#24]
2.1h as a version isn’t recognized as a valid version and blocks the integration from loading. 

Check https://developers.home-assistant.io/docs/creating_integration_manifest/

seems home assistant doesn’t like the letter.

`2022-04-13 06:44:51 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration ‘neosmartblinds’ does not have a valid version key (2.1h) in the manifest file and was blocked from loading.`

**Comment by altShiftDev** [comment]
Ya, any updates on this? @marshes do you have a quick fix?

**Comment by marshes** [comment]
I left a comment here: https://community.home-assistant.io/t/custom-component-neosmartblinds-cover/156209/40?u=marshes

easy fix for this is to modify your manifest.json file by hand and change the version key from 2.1h  to 2.1 or 2.1.8.   My manifest predates more recent updates to this repo, so it still has 1.2.3 which works just fine. DM through the HA community forum if you need a hand.

**Comment by mtgeekman** [comment]
Sorry about that, the release with that in the manifest has been removed as it wasn't meant for anyone to actually download/use I'll keep trying to get this working correctly.
