### ISSUE TITLE
 Integration 'neosmartblinds' not found.

### ISSUE THREAD

**Issue by tomskidoodle** [mtgeekman/Home_Assistant_NeoSmartBlinds#26]
I persistently get this error in HA.  I hoped the latest release would help, but no joy.  I can find nothing to reference this anywhere else.

Installed through HACS

Full error: **Platform error cover.neosmartblinds - Integration 'neosmartblinds' not found.**

configuration.yaml entry:

cover:
  - platform: neosmartblinds
    name: Living Room Blind
    host: 192.168.86.37
    hub_id: TUkrCvA1VK6c95R2j6SwfQ
    protocol: http
    port: 8838
    blind_code: 083.242-01
    close_time: 30
    rail: 1
    percent_support: 2
    motor_code: k2
    start_position: 50

**Comment by keithr59** [comment]
There is an outstanding issue with the HACS installation where it creates an extra sub folder #23.

You will need to manually move the files to the correct location as per the manual installation instructions for the integration to work.

**Comment by tomskidoodle** [comment]
Thanks, this has been resolved as you suggested.
