### ISSUE TITLE
Incompatible with HA 2022.7

### ISSUE THREAD

**Issue by mic-mccann** [mtgeekman/Home_Assistant_NeoSmartBlinds#28]
Hi since updating to HA 2022.7 Neosmartblinds integration has stopped working.

The error msg I get is 

Platform error cover.neosmartblinds - Requirements for neosmartblinds not found: ['requests==2.27.1'].

This may be due to 2022.7 update to Python 3.10.

**Comment by mic-mccann** [comment]
I fixed this by updating the manifest.json file

From:

  "requirements": ["requests==2.27.1"]

To:

  "requirements": ["requests==2.28.1"]

**Comment by rjm12rjm12** [comment]
I tried modifying this, but after reset HA still gives me the 2.27.1 error, even though the file shows 2.28.1.

**Comment by robertw** [comment]
Made the change "requirements": ["requests==2.28.1"] worked fine ...... thanks

**Comment by mic-mccann** [comment]
> I tried modifying this, but after reset HA still gives me the 2.27.1 error, even though the file shows 2.28.1.

Try uninstalling the plugin.

If you installed the plugin via HACS uninstall via the UI. Then restart HA confirming the component has been the removed

If you installed the plugin via dropping it into config/custom_components delete the neosmartblinds folder. Then restart HA confirming the component has been the removed. 

Download the neosmartblinds folder from this GitHub page. Change the relevant line in the manifest.json file

From:

"requirements": ["requests==2.27.1"]

To:

"requirements": ["requests==2.28.1"]

Put the neosmartblinds folder in config/custom_components. Restart HA. 

Let me know if you have any further problems.

**Comment by rjm12rjm12** [comment]
After following the above, it worked.
Thanks

**Comment by mnunes7** [comment]
@mic-mccann I have tried your workaround above but I still receive: 

Platform error cover.neosmartblinds - Integration 'neosmartblinds' not found.

**Comment by mtgeekman** [comment]
A new version has been released and should take care of the incompatibility.
