### ISSUE TITLE
Connection Reset by Peer

### ISSUE THREAD

**Issue by BillyFKidney** [mtgeekman/Home_Assistant_NeoSmartBlinds#29]
I’m unable to control my blinds after a reboot (no upgrades) and the errors I’m receiving are:

```
This error originated from a custom integration.

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:119 
Integration: neosmartblinds (documentation) 
First occurred: July 8, 2022, 10:02:52 AM (20 occurrences) 
Last logged: 8:47:32 AM

[Errno 104] Connection reset by peer 
```

```
This error originated from a custom integration.

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:118 
Integration: neosmartblinds (documentation) 
First occurred: July 8, 2022, 10:02:52 AM (20 occurrences) 
Last logged: 8:47:32 AM

URL: http://192.168.40.252:8838/neo/v1/transmit 
```

```
This error originated from a custom integration.

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:117 
Integration: neosmartblinds (documentation) 
First occurred: July 8, 2022, 10:02:52 AM (20 occurrences) 
Last logged: 8:47:32 AM

Parameters: {'id': 'ID_STUFF-xtDrkHw', 'command': '209.169-15-gp', 'hash': '0488248'}
Parameters: {'id': 'ID_STUFF-xtDrkHw', 'command': '209.169-15-gp', 'hash': '0680512'}
Parameters: {'id': 'ID_STUFF-xtDrkHw', 'command': '209.169-15-up', 'hash': '0311099'}
Parameters: {'id': 'ID_STUFF-xtDrkHw', 'command': '239.005-15-sp', 'hash': '0686686'}
Parameters: {'id': 'ID_STUFF-xtDrkHw', 'command': '239.005-15-sp', 'hash': '0353865'}
```
*Changed mildly to protect data

Core-2022.6.7
Python 3.9.12
HAOS 8.2
HACS 1.25.5

any ideas?

**Comment by gee-jay-bee** [comment]
Have you tried power cycling the hub itself? I have very rarely seen cases where my hub becomes unresponsive and a power cycle does the trick ...

**Comment by BillyFKidney** [comment]
> Have you tried power cycling the hub itself? I have very rarely seen cases where my hub becomes unresponsive and a power cycle does the trick ...

Twice, the NeoBlinds app works flawlessly.

**Comment by BillyFKidney** [comment]
I unplugged the NeoSmartBlinds hub for five minutes, restored power, then restarted Home Assistant.

Attempts to send commands result in the same errors:
![image](https://user-images.githubusercontent.com/65253277/178611324-fa710bb6-2250-402c-8f85-99c09e74cf37.png)


Any ideas?

**Comment by gee-jay-bee** [comment]
No good ideas 😊 

Just to be totally sure, the hub still has the same IP? No chance that it got a new one and something else is responding to ping?

**Comment by gee-jay-bee** [comment]
Can you try enabling debug logs for custom_components.neo_smart_blinds?

Might be interesting to see how far the command processing gets.
If there's a TX log but the blind doesn't move and there is no RX log then it may suggest something wrong with the command being sent (maybe motor code?).

Could you also share a sanitised version of your cover config as well?

A more speculative change would be to switch to tcp from http. I can't really see how it could help as i have observed same behaviour with both but maybe it would give us another clue to investigate ...

**Comment by BillyFKidney** [comment]
I enabled logging (double folder is a HACS issue) in my **configuration.yaml**
```
logger:
  default: warning
  logs:
    custom_components.neosmartblinds.neo_smart_blind: debug
```

Logs:
```
This error originated from a custom integration.

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:117 
Integration: neosmartblinds (documentation) 
First occurred: 5:39:51 PM (1 occurrences) 
Last logged: 5:39:51 PM

Parameters: {'id': 'My_ID', 'command': '209.169-15-sp', 'hash': '0015447'}
```

```
This error originated from a custom integration.

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:118 
Integration: neosmartblinds (documentation) 
First occurred: 5:39:51 PM (1 occurrences) 
Last logged: 5:39:51 PM

URL: http://192.168.40.252:8838/neo/v1/transmit
```

```
This error originated from a custom integration.

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:119 
Integration: neosmartblinds (documentation) 
First occurred: 5:39:51 PM (1 occurrences) 
Last logged: 5:39:51 PM

Server disconnected
```

```
This error originated from a custom integration.

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:46 
Integration: neosmartblinds (documentation) 
First occurred: 5:39:51 PM (1 occurrences) 
Last logged: 5:39:51 PM

209.169-15, disconnected from hub: ServerDisconnectedError('Server disconnected')
```

My **cover.yaml** (referenced by **configuration.yaml**)
```
# Cover entry
  
# Neo SmartBlinds
- platform: neosmartblinds
  name: Living Room Blinds
  host: !secret NeoBlinds_host
  hub_id: !secret NeoBlinds_hub_id
  protocol: http
  port: 8838
  blind_code: 239.005-15
  close_time: 99
    
- platform: neosmartblinds
  name: Master Bedroom Room Blinds
  host: !secret NeoBlinds_host
  hub_id: !secret NeoBlinds_hub_id
  protocol: http
  port: 8838
  blind_code: 209.169-15
  close_time: 99
```

**Comment by gee-jay-bee** [comment]
IIRC, the debug logs are only in the full log.
You either have to push "load full log" button in the UI to see them or copy out of the .log file in the config directory.

**Comment by BillyFKidney** [comment]
```
2022-07-15 13:28:46 INFO (MainThread) [custom_components.neosmartblinds.cover] Master Bedroom Room Blinds stop
2022-07-15 13:28:46 ERROR (MainThread) [custom_components.neosmartblinds.neo_smart_blind] Parameters: {'id': 'My_ID', 'command': '209.169-15-sp', 'hash': '0495827'}
2022-07-15 13:28:46 ERROR (MainThread) [custom_components.neosmartblinds.neo_smart_blind] URL: http://192.168.40.252:8838/neo/v1/transmit
2022-07-15 13:28:46 ERROR (MainThread) [custom_components.neosmartblinds.neo_smart_blind] [Errno 104] Connection reset by peer
2022-07-15 13:30:06 INFO (MainThread) [custom_components.neosmartblinds.cover] Master Bedroom Room Blinds stop
2022-07-15 13:30:06 ERROR (MainThread) [custom_components.neosmartblinds.neo_smart_blind] Parameters: {'id': 'My_ID', 'command': '209.169-15-sp', 'hash': '0530208'}
2022-07-15 13:30:06 ERROR (MainThread) [custom_components.neosmartblinds.neo_smart_blind] URL: http://192.168.40.252:8838/neo/v1/transmit
2022-07-15 13:30:06 ERROR (MainThread) [custom_components.neosmartblinds.neo_smart_blind] [Errno 104] Connection reset by peer
```

That's the full log

**Comment by gee-jay-bee** [comment]
Now that's got me confused.

If I include this in my config:

`
logger:
  default: error
  logs:
    custom_components.neosmartblinds: debug
`

I get a full breakdown like this:

'
2022-07-15 21:22:32 DEBUG (MainThread) [custom_components.neosmartblinds.neo_smart_blind] 094.229-01, issuing command
2022-07-15 21:22:32 DEBUG (MainThread) [custom_components.neosmartblinds.neo_smart_blind] 094.229-01, Tx: 094.229-01-dn

2022-07-15 21:22:32 DEBUG (MainThread) [custom_components.neosmartblinds.neo_smart_blind] 094.229-01, Rx: 094.229-01-dn

2022-07-15 21:22:32 INFO (MainThread) [custom_components.neosmartblinds.neo_smart_blind] 094.229-01, connected to hub
2022-07-15 21:22:32 INFO (MainThread) [custom_components.neosmartblinds.cover] Office closing to 0
2022-07-15 21:22:32 INFO (MainThread) [custom_components.neosmartblinds.cover] Office sleeping for 16.0 to allow for close to 0, elapsed=0
2022-07-15 21:22:48 INFO (MainThread) [custom_components.neosmartblinds.cover] Office move done 0
'

**Comment by gee-jay-bee** [comment]
Ah, I note that my debug will differ because I am using tcp not http. It looks like http debug will be missing if the get() function raises an exception.

I can't see anything obviously odd about config. The message implies that the the hub is disconnecting (the log timestamps are all close so no sign of a timeout) so I guess it doesn't like the incoming request url. Motor code and the hub ID are what I'd check first because everything else looks reasonable (assuming blind code is ok). 

Also, tcp doesn't use the hub ID so changing to that (and port to 8839) could reveal a difference.

Sorry this is a bit trial & error

**Comment by BillyFKidney** [comment]
> Ah, I note that my debug will differ because I am using tcp not http. It looks like http debug will be missing if the get() function raises an exception.
> 
> I can't see anything obviously odd about config. The message implies that the the hub is disconnecting (the log timestamps are all close so no sign of a timeout) so I guess it doesn't like the incoming request url. Motor code and the hub ID are what I'd check first because everything else looks reasonable (assuming blind code is ok).
> 
> Also, tcp doesn't use the hub ID so changing to that (and port to 8839) could reveal a difference.
> 
> Sorry this is a bit trial & error

Wonky as could be! I've not changed anything in my configuration yet...
Are there any negatives moving to TCP?

**Comment by gee-jay-bee** [comment]
Right so that shows that the command is being sent and then the hub is killing the TCP connection.

Did you try specifying the motor code? I see it isn't in your config. My hub doesn't need it but apparently some do.

**Comment by BillyFKidney** [comment]
> Right so that shows that the command is being sent and then the hub is killing the TCP connection.
> 
> Did you try specifying the motor code? I see it isn't in your config. My hub doesn't need it but apparently some do.

I added the motor code (bf) but it didn’t change anything.
Is there any way to log into the hub to test? The NeoSmartBlinds app works flawlessly which I didn’t expect.

```
2022-07-16 14:22:36 DEBUG (MainThread) [custom_components.neosmartblinds.neo_smart_blind] 239.005-15, Tx: 239.005-15-gp!bf
2022-07-16 14:22:36 WARNING (MainThread) [custom_components.neosmartblinds.neo_smart_blind] 239.005-15, disconnected from hub: ConnectionResetError(104, 'Connection reset by peer')
2022-07-16 14:23:03 WARNING (MainThread) [custom_components.eufy_security] eufy_security - no devices available yet
2022-07-16 14:23:12 DEBUG (MainThread) [custom_components.neosmartblinds.neo_smart_blind] 239.005-15, Tx: 239.005-15-gp!bf
```

**Comment by Bacichetti** [comment]
Yes. @BillyFKidney can you send a message to tech@neosmartblinds.com with your account e-mail? I'll check is on Monday. Also, have you tried sending the commands using a different program, like packetsender ?

**Comment by mtgeekman** [comment]
Are both your Neo Hub and Home Assistant server on the same subnet?

**Comment by BillyFKidney** [comment]
> Are both your Neo Hub and Home Assistant server on the same subnet?

Yes, there have been zero changes other than upgrading Home Assistant to 2022.7.5

**Comment by mtgeekman** [comment]
@BillyFKidney did you ever hear anything back from the tech@neosmartblinds.com email?

**Comment by BillyFKidney** [comment]
> @BillyFKidney did you ever hear anything back from the [tech@neosmartblinds.com](mailto:tech@neosmartblinds.com) email?

Yeah, they were helpful.
