### ISSUE TITLE
Does this support bottom-up/top-down blinds?

### ISSUE THREAD

**Issue by jgrn307** [mtgeekman/Home_Assistant_NeoSmartBlinds#3]
We have NeoSmartBlinds but some of them are the bottom-up/top-down (so are configured by the "rail" that moves, either the bottom, the top, or both at the same time).  Does this work with that type?

**Comment by mtgeekman** [comment]
Top-down/bottom-up is somewhat of a work in progress. 

I haven't been able to do a lot of work on it as I do not have any top-down/bottom-up blinds to do any testing on.

**Comment by mtgeekman** [comment]
https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds/releases/tag/1.3

can you give this release a shot?

**Comment by mtgeekman** [comment]
This should be working now.

**Comment by jgrn307** [comment]
Sorry, I finally got neosmartblinds working and the top-down/bottom-up isn't quite working right (or needs some additional tweaks).  I've opened an issue at https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds/issues/18
