### ISSUE TITLE
Platform error cover.neosmartblinds - Integration 'neosmartblinds' not found.

### ISSUE THREAD

**Issue by kylev12** [mtgeekman/Home_Assistant_NeoSmartBlinds#30]
Hi there,
After a recent HA update I experienced the issue with " Platform error cover.neosmartblinds - Requirements for neosmartblinds not found: ['requests==2.27.1']. "

I had followed the recommendation in issue #28 but after uninstall through HACS and manually placing the config/custom_components/ directory I am now receiving error "Platform error cover.neosmartblinds - Integration 'neosmartblinds' not found."

Have done a HA restart, have tried to install it via HACS again and still no luck unfortunately.

Any ideas?
Cheers,
Kyle

**Comment by mtgeekman** [comment]
the quick and dirty fix is to update the manifest.json to use "requests==2.28.1"

I am going to put out a new version as soon as I can,  out of town right now so I don't have access to update it.

**Comment by karanvivekbhargava** [comment]
No worries. Thank you for keeping us updated 👍

**Comment by olivierjag2** [comment]
Hi 

I remove folder and i recopy. I modify the manifest file and I have this error message
The system cannot restart because the configuration is not valid: Platform error cover.neosmartblinds - Requirements for neosmartblinds not found: ['requests==2.27.1'].

Can you help me?

**Comment by mnunes7** [comment]
@mtgeekman i'm also having the same issue:

- I have changed changed the manifest.json "requirements": ["requests==2.28.1"]
- When I check configuration to restart home assistant I receive: 
Platform error cover.neosmartblinds - Integration 'neosmartblinds' not found.

Bare in mind this is the first time I have tried to use this custom component.

**Comment by RumenBlack84** [comment]
I am running into the same issue. I have tried the above workaround listed about changing the manifest.json without effect.

Has this issue been resolved or is there a work around?

**Comment by mtgeekman** [comment]
For those with this issue, please give the latest release a try, 2.2
