### ISSUE TITLE
Rail "3" for Top-Down,Bottom-Up Blinds?

### ISSUE THREAD

**Issue by jgrn307** [mtgeekman/Home_Assistant_NeoSmartBlinds#31]
I'm finally getting back into investigating neo smart blind usage for my setup -- one thing that appears to be missing is the ability to push BOTH rails on a TD/BU blind together (in the remote, it is usually listed as rail "3" which just means rail 1 and 2 at the same time).  Is there some way to add this feature?

**Comment by gee-jay-bee** [comment]
I think it's possible to do this in a couple of ways, with increasing difficulty:

- If you only need the ability to control both blinds without any kind of position tracking / state management in the integration, the check that the rail config option is either 1 or 2 could be extended to allow 3. The commands would then need to deal with the additional rail.
- if you want the integration to allow commands to be sent to rails 1, 2 & 3 and try to track state / position then this can probably build on the parent group feature added in v2.2 (it's almost the same logic - the integration would see the attempt to send the same command to both rails and then only actually send to rail 3).

**Comment by jgrn307** [comment]
Was this ever integrated?
