### ISSUE TITLE
Feature Request: Ability to Detect Blind Position

### ISSUE THREAD

**Issue by BillyFKidney** [mtgeekman/Home_Assistant_NeoSmartBlinds#33]
Is it possible to detect the blind's position?

Often one of the four blinds in our home doesn't respond to the first time we send a command. I'd like to be able to resend the command if the blind is not in the correct position.

Additionally, if somebody uses the RF remote then Home Assistant has the wrong position in COVER.

**Comment by mtgeekman** [comment]
Currently, the API does not support this, we have been working with one of the developers to try and prioritize adding it to their API, but it takes time.
