### ISSUE TITLE
No local access?

### ISSUE THREAD

**Issue by cjoha** [mtgeekman/Home_Assistant_NeoSmartBlinds#35]
As of the weekend, I have lost control of my Neo Smart Blinds controller (wooden Luxaflux). I have a feeling that an update has been pushed which has closed off the local API access, or an API update has been pushed? I have a static IP assigned to the Neo Smart Controller. The Home Assistant server itself can happily ping the neo controller, but from the logs I can see that it cannot connect on TCP port 8838, using the path /neo/v1/transmit

Logger: custom_components.neosmartblinds.neo_smart_blind
Source: custom_components/neosmartblinds/neo_smart_blind.py:315
Integration: neosmartblinds (documentation, issues)
First occurred: 27 November 2022 at 18:49:11 (45 occurrences)
Last logged: 08:12:00

Parameters: {'id': '23004e000251353532373238', 'command': '073.065-02-up', 'hash': '0808264'}
URL: http://192.168.8.245:8838/neo/v1/transmit
Cannot connect to host [192.168.8.245:8838](http://192.168.8.245:8838/) ssl:default [Connect call failed ('192.168.8.245', 8838)]
Parameters: {'id': '23004e000251353532373238', 'command': '073.065-03-up', 'hash': '0343382'}
Parameters: {'id': '23004e000251353532373238', 'command': '073.065-15-up', 'hash': '0854171'}

I have reached out to Neo Tech Support to see if they have made any changes to their API structure, or their local access policies.

**Comment by mtgeekman** [comment]
Can you tell me what model smart hub you have? I am as far as I am aware no one else is having any issues with control and mine is working great this morning.

**Comment by cjoha** [comment]
Hi there. It is the wooden effect one, https://daks2k3a4ib2z.cloudfront.net/5567170d81b211231d4323eb/56565ddb7f808ada5a6b9bdb_Web-Controller-02-smaller.png.

I'll check again later on to see if the automations trigger.

**Comment by cjoha** [comment]
I'm closing this out. Neo confirmed no changes on their side. This must be a local issue.
