### ISSUE TITLE
issues after update to core today

### ISSUE THREAD

**Issue by gmbestmac** [mtgeekman/Home_Assistant_NeoSmartBlinds#40]
after the latest update i'm getting the following error - any advice?

Last logged: 2:40:48 PM

012.037-01, disconnected from hub: ConnectionResetError(104, 'Connection reset by peer')
Parameters: {'id': 'qui-i0c_WleIACyHRXKSMQ-', 'command': '012.037-00-dn!wt', 'hash': '0696859'}
URL: http://192.168.86.110:8838/neo/v1/transmit
[Errno 104] Connection reset by peer
012.037-00, disconnected from hub: ClientOSError(104, 'Connection reset by peer')

**Comment by taelinn** [comment]
I think this is a known issue. Normally restarting (unplug it for 10 seconds) the hub will resolve it.

**Comment by gmbestmac** [comment]
Yeah a reboot of the hub solved the issue - should have tried the good ole turn it off and turn it back on again first!
