### ISSUE TITLE
Platform error cover.neosmartblinds - Requirements for neosmartblinds not found: ['requests==2.28.2'].

### ISSUE THREAD

**Issue by joelbibeau** [mtgeekman/Home_Assistant_NeoSmartBlinds#41]
Since a few days nothing works for me and I have this error. ideas?

**Comment by mtgeekman** [comment]
I just made some changes to the code base and created a new release. 

If you used HACS you can update through there.

**Comment by tome88** [comment]
> hi @mtgeekman I can't find neosmartblinds when i search for it in HACS in the Integrations or Frontend?

scrap that, added your repo - got it!

**Comment by tome88** [comment]
hi @mtgeekman after installing via HACS I'm still getting:
Platform error cover.neosmartblinds - Requirements for neosmartblinds not found: ['requests==2.28.2']
when checking my config file. I've added the below into my config.yaml file XX's to redact info, but was working before recent HA upgrade:

cover:
   - platform: neosmartblinds
    name: blockoutmaster
    host: XXX.XXX.XX.XX
    hub_id: cFXXXXXXXXXXXXXXXXXXXKQ
    protocol: tcp
    port: 8839
    blind_code: XXX.XXX-00-
    close_time: 10
    rail: 1
    percent_support: 1
    motor_code: wt
    start_position: 0
    parent_group: XXX.XXX-15

**Comment by keithr59** [comment]
@tome88 If you have recently upgraded HA Core to 2023.6.0 you should be able to fix your problem by editing the manifest.json file in config > custom_components > neosmartblinds and change the line 

  "requirements": ["requests==2.28.2"]

to

  "requirements": ["requests==2.31.0"]

and then restart HA.

**Comment by tome88** [comment]
Thanks for the quick response @keithr59 however upon doing that I get the error:
Invalid config for [cover.neosmartblinds]: [parent_group] is an invalid option for [cover.neosmartblinds]. Check: cover.neosmartblinds->parent_group. (See ?, line ?).

**Comment by keithr59** [comment]
@tome88 Unfortunately that is the extent of my knowledge exhausted. Maybe try temporarily commenting out the parent_group entry in your config and see if that makes a difference. I don't use parent_group in my own set up.

**Comment by malo-ph** [comment]
I got the same error after I upgrade the HACS neoSmart blinds module. I just decide to rollback to the previous version for now.

Thanks,

Philippe

Le 8 juin 2023 à 07:36, keithr59 ***@***.***> a écrit :

﻿

@tome88<https://github.com/tome88> Unfortunately that is the extent of my knowledge exhausted. Maybe try temporarily commenting out the parent_group entry in your config and see if that makes a difference. I don't use parent_group in my own set up.

**Comment by malo-ph** [comment]
Sorry my last email was about the

parent_group

Thanks,

Philippe

Le 8 juin 2023 à 07:16, tome88 ***@***.***> a écrit :

parent_group

**Comment by rjm12rjm12** [comment]
> @tome88 If you have recently upgraded HA Core to 2023.6.0 you should be able to fix your problem by editing the manifest.json file in config > custom_components > neosmartblinds and change the line
> 
> "requirements": ["requests==2.28.2"]
> 
> to
> 
> "requirements": ["requests==2.31.0"]
> 
> and then restart HA.

This solved my issue, thanks.

**Comment by joelbibeau** [comment]
Thanks all. Its working for me

**Comment by keithr59** [comment]
@tome88 I have done some digging around and it looks like the latest HACS update has downloaded an old release as the _manifest.json_ file on my system says it is version 1.5. (Group codes were introduced in version 2..2).

If you go to https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds/releases, extract the **Source.code** zip file, copy the whole **neosmartblinds** folder from **custom_components/** to your own **config/custom_components/** directory and then restart HA it should install the correct version.

**Comment by bktz** [comment]
> @tome88 I have done some digging around and it looks like the latest HACS update has downloaded an old release as the _manifest.json_ file on my system says it is version 1.5. (Group codes were introduced in version 2..2).
> 
> If you go to https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds/releases, extract the **Source.code** zip file, copy the whole **neosmartblinds** folder from **custom_components/** to your own **config/custom_components/** directory and then restart HA it should install the correct version.

I followed these steps (but downloaded a zip of master and updated `manifest.json` to `"requirements": ["requests==2.31.0"]`). That resolved the parent group issue for me.

Thanks

**Comment by BillyFKidney** [comment]
To make the code less brittle change your **manifest.json** to the following:
```
{
  "domain": "neosmartblinds",
  "name": "NeoSmartBlinds",
  "version": "1.5",
  "documentation": "https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds/blob/master/README.md",
  "codeowners": ["4n0nD3v3l0p3r","mtgeekman","clara-j"],
  "requirements": ["requests>=2.31.0"]
}
```


I found that Home Assistant would not reboot until I disabled **Cover.py**

1) Disable **Cover.py**
2) Edit **Manifest.json**
3) Restart Home Assistant Core
4) Enable **Cover.py**
5) Restart Home Assistant Core
Everything should work

**Comment by Tooflawless** [comment]
> > @tome88 If you have recently upgraded HA Core to 2023.6.0 you should be able to fix your problem by editing the manifest.json file in config > custom_components > neosmartblinds and change the line
> > "requirements": ["requests==2.28.2"]
> > to
> > "requirements": ["requests==2.31.0"]
> > and then restart HA.
> 
> This solved my issue, thanks.

this solved it for me and I had to comment out parent group
Thank you!

**Comment by tome88** [comment]
> > > @tome88 If you have recently upgraded HA Core to 2023.6.0 you should be able to fix your problem by editing the manifest.json file in config > custom_components > neosmartblinds and change the line
> > > "requirements": ["requests==2.28.2"]
> > > to
> > > "requirements": ["requests==2.31.0"]
> > > and then restart HA.
> > 
> > 
> > This solved my issue, thanks.
> 
> this solved it for me and I had to comment out parent group Thank you!

resolved! thanks so much all! I didn't need to comment out the parent_group for some reason. I just added in json file per @BillyFKidney and used the source.zip files 👍

**Comment by mnunes7** [comment]
> To make the code less brittle change your **manifest.json** to the following:
> 
> ```
> {
>   "domain": "neosmartblinds",
>   "name": "NeoSmartBlinds",
>   "version": "1.5",
>   "documentation": "https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds/blob/master/README.md",
>   "codeowners": ["4n0nD3v3l0p3r","mtgeekman","clara-j"],
>   "requirements": ["requests>=2.31.0"]
> }
> ```
> 
> I found that Home Assistant would not reboot until I disabled **Cover.py**
> 
> 1. Disable **Cover.py**
> 2. Edit **Manifest.json**
> 3. Restart Home Assistant Core
> 4. Enable **Cover.py**
> 5. Restart Home Assistant Core
>    Everything should work

How do you disable to the Cover.py and reenable it?

**Comment by mtgeekman** [comment]
This should be resolved going forward with the latest release. Thanks @BillyFKidney  should have done that to begin with!
