### ISSUE TITLE
No longer working. 

### ISSUE THREAD

**Issue by smarthousetips** [mtgeekman/Home_Assistant_NeoSmartBlinds#42]
No configurations have changed but this stopped working yesterday and hasn't worked since. Restarted and still not working.

Parameters: {'id': 'RG7MCfgXWCqacbsEtIal1g', 'command': '183.159-01-i2!bf', 'hash': '0381191'}
URL: http://192.168.7.4:8838/neo/v1/transmit
[Errno 104] Connection reset by peer

URL: http://192.168.7.4:8838/neo/v1/transmit
[Errno 104] Connection reset by peer
Parameters: {'id': 'RG7MCfgXWCqacbsEtIal1g', 'command': '183.159-15-up!bf', 'hash': '0027510'}
Parameters: {'id': 'RG7MCfgXWCqacbsEtIal1g', 'command': '183.159-15-up!bf', 'hash': '0675603'}
Parameters: {'id': 'RG7MCfgXWCqacbsEtIal1g', 'command': '183.159-15-up!bf', 'hash': '0928555'}

**Comment by mtgeekman** [comment]
Did you try restarting your hub?

**Comment by sco0ts** [comment]
As mtgeekman said but not simply restarting HA. You need to restart the base machine or VM that HA is in.
