### ISSUE TITLE
Latest version doesnt move to favourite position when 50 or 51 is requested

### ISSUE THREAD

**Issue by ZEi20T** [mtgeekman/Home_Assistant_NeoSmartBlinds#5]
didnt notice a config change required, but i replaced the folder with the new version.

called 'position: 50' and 51, just in case, still it didnt move.

open and close functions both work fine.

put the old version back and working again.

i have an awning, if that helps.

thanks!

**Comment by clara-j** [comment]
I just upgraded to the latest 1.2.1 version and tested it with my setup and it is working for me with favourite 1/2 setting it to 50/51.

Does your controller support both favourite positions?  Do you see the option to set two favourites in the NeoSmartBlinds app?

**Comment by clara-j** [comment]
I am suspecting that controllers that only support 1 favourite don't work with the code for favourite 1, and require the old code.

If your device only supports one favourite, could you try opening the const.py with the 1.2.1 code and change the following.
CMD_FAV_1 = "i1"
to 
CMD_FAV_1 = "gp"

Alternatively you can try my branch with a potential fix.  If it works I will ask for a merge back to the mtgeekman's repo 
https://github.com/clara-j/Home_Assistant_NeoSmartBlinds

**Comment by ZEi20T** [comment]
yeah my controller only has 1 fav position.

my motor code is 'wt' if that helps

ill make the code changes later today, ive been reading the other thread

thanks for your replies!

**Comment by mtgeekman** [comment]
@ZEi20T Can we convince you to give the latest files in the repo a try?

**Comment by ZEi20T** [comment]
thank you, i will try it shortly and let you know

**Comment by ZEi20T** [comment]
sorry guys, no luck

**Comment by clara-j** [comment]
Just to confirm, you are using the latest code from the master branch, and not the last release?

Can you try using the tilt slider also for pulling up the factories.  You can set it to less than 50 for favourite 1, or greater than 51 for favourite 2.  I assume your controller won't support favourite 2 though based on the previous code not working.

After you do that can you go to Configuration->Logs and see if there are any errors/warning.

**Comment by ZEi20T** [comment]
OK. no, sorry, i wasn't downloading the master branch. i have now.

0 - 50 - 100 positions work as expected. my controller doesn't offer a 2nd fav position.

adding percent_support = 1 weirdly stops HA from completely loading. may be related to my version of HA - 2021.4.6 docker image

2021-04-28 07:21:07 ERROR (MainThread) [root] Uncaught exception
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

**Comment by clara-j** [comment]
Great, glad the update got you back to things working as expected for your setup.  Hard to test and know for sure since I only have my own unit for testing.

Can you confirm if you also updated the cover.py file.  That is what was updated for the new percent_support parameter.  
I'm not sure why setting it would cause HA to not load otherwise.  

Maybe you can post this in the any % issue.  If everything is working for you now I will close this one off at least as resolved.

**Comment by mtgeekman** [comment]
Marking as closed.  Please add comments to the [Any % Request](https://github.com/mtgeekman/Home_Assistant_NeoSmartBlinds/issues/8)
