### ISSUE TITLE
Proposed change to favourites

### ISSUE THREAD

**Issue by clara-j** [mtgeekman/Home_Assistant_NeoSmartBlinds#9]
I was thinking of changing the favourite settings from 50/51 on the position slider to the tilt slider.

Here are the reasons for the changes.

- Once the support for percentage is added there is a conflict where you can not set the requested position to these two values using the slider as they take precedent.
- Currently the neoblinds do not work if you try to expose them through the HomeKit integration.  This is due to tilt positioning not currently being enabled.

So by enabling tilt positioning and moving the favourite to that resolves both of these issues.  I have tested HomeKit locally and it seems to be working so far.  But haven't done work for the tilt and favourites yet.

Any issues with this approach, I know this is a breaking change for people that currently have a setup with favourites based on the 50/51 positioning, so open to other thoughts.

**Comment by mtgeekman** [comment]
That's not a bad idea.  The only real option we have is to put out a release that announces the breaking changes in the logs.  but this also requires people to check the logs. 

Or, we put out a whole second version.  I do not like this idea s much, maintaining multiple code bases that are nearly identical doesn't sound fun at all.

**Comment by clara-j** [comment]
Exactly, but since at the moment updates are manual it should hopefully get noticed, and switching to tilt vs position in automation hopefully won't be too cumbersome for people that currently have them.  And worse case people can stay on the older version if necessary.  

If it is a huge issue I could see what would be needed to maybe allow a config parameter to fallback to the old version if it isn't too hard.

I agree, I wouldn't want to support to code branches.

**Comment by mtgeekman** [comment]
Thanks for joining this repo.  Hopefully, between the two of us, we can do some neat stuff going forward.  

I have a discord that's pretty quiet if you want to chat at all : https://discord.gg/NCPmwVJh

**Comment by clara-j** [comment]
No problem, glad to contribute.  Just started to migrate to HA and the better the support for my blinds the better.

Looks like implementing this change without breaking existing users shouldn't be too hard.  Have it so tilt will work for all users, but if percent support is disabled it will still use position 50/51.  I have a working version now with percent positioning, HomeKit support, and the enabling of tilt for selecting a favourite.  Just need to do a bit more testing and will likely push it tomorrow.  Also need to update the readme still.

**Comment by mtgeekman** [comment]
Are we good to close this one?

**Comment by clara-j** [comment]
Ya, I think so.  I just didn't close it yet to make sure no one had any issues with the latest version.  But we can handle that as a new issue if anything comes up.

**Comment by mtgeekman** [comment]
sounds good, closing.
